=== EmpregoLigado/praxis/docs/schema/index.json
{
    "id": "index-schema#",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "schema for a Praxis API definition",
    "type": "object",
    "required": [ "info", "resources", "schemas", "traits" ],
    "properties": {
        "info" : {
          "$ref": "#/definitions/info"
        },
        "resources" : {
          "type": "object",
          "patternProperties": {
            ".*": { "$ref": "resource.json#"}
          }
        },
        "schemas" : {
          "type": "object",
          "patternProperties": {
            ".*": { "$ref": "media_type.json#"}
          }
        },
        "traits": {
          "type": "object"
        }
    },
    "additionalProperties": false,

    "definitions": {
      "info": {
        "description": "schema for top level API info",
        "type" : "object",
        "properties" : {
            "schema_version": { "type" : "string" },
            "name": {"type" : "string" },
            "title": {"type" : "string" },
            "description": {"type" : "string" },
            "base_path": { "type" : "string" },
            "version_with": { "type" : ["string","array"] },
            "endpoint": { "type" : "string" },
            "consumes": {
              "type": "array",
              "items": { "type": "string" }
            },
            "produces": {
              "type": "array",
              "items": { "type": "string" }
            },
            "base_params": { "type": "object" }
        },
        "required": ["schema_version"],
        "additionalProperties": false
      }
    }
}

=== EmpregoLigado/praxis/test.json
{
  "info": {
    "schema_version": "1.0",
    "name": "bloggy",
    "title": "A Blog API example application",
    "description": "This is the 1.0 version of Bloggy",
    "base_path": "/api/v1.0",
    "version_with": "path",
    "consumes": [
      "json",
      "x-www-form-urlencoded",
      "form-data"
    ],
    "produces": [
      "json",
      "form-data"
    ]
  },
  "resources": {
    "V1-ResourceDefinitions-Blogs": {
      "description": null,
      "media_type": {
        "name": "V1::MediaTypes::Blog",
        "family": "hash",
        "id": "V1-MediaTypes-Blog",
        "key": {
          "type": {
            "name": "Symbol",
            "family": "string",
            "id": "Attributor-Symbol"
          }
        }
      },
      "actions": [
        {
          "description": null,
          "name": "index",
          "metadata": {
          },
          "responses": {
            "ok": {
              "description": "Standard response for successful HTTP requests.",
              "status": 200,
              "headers": {
              },
              "payload": {
                "name": "V1::MediaTypes::Blog::Collection",
                "family": "array",
                "id": "V1-MediaTypes-Blog-Collection",
                "options": {
                },
                "member_attribute": {
                  "options": {
                    "reference": "V1::MediaTypes::Blog"
                  },
                  "type": {
                    "name": "V1::MediaTypes::Blog",
                    "family": "hash",
                    "id": "V1-MediaTypes-Blog",
                    "key": {
                      "type": {
                        "name": "Symbol",
                        "family": "string",
                        "id": "Attributor-Symbol"
                      }
                    }
                  }
                },
                "examples": {
                  "json": {
                    "content_type": "application/vnd.bloggy.blog+json; type=collection",
                    "body": "[\n  {\n    \"id\": 452,\n    \"href\": \"/api/v1.0/blogs/452\",\n    \"name\": \"Failed to generate example for /\\\\/api\\\\/accounts\\\\/\\\\d+/ : Sorry, \\\"\\\\d+\\\" is too vague, try setting a range: \\\"\\\\d{1, 5}\\\"\",\n    \"description\": \"sulfotelluride\",\n    \"url\": \"example.com/blogs/452\",\n    \"timestamps\": {\n      \"created_at\": \"2012-11-17T00:00:00+00:00\",\n      \"updated_at\": \"2014-08-10T00:00:00+00:00\"\n    },\n    \"owner\": {\n      \"id\": 442,\n      \"href\": \"/api/v1.0/users/442\",\n      \"first\": \"Darrell\",\n      \"last\": \"O'Connell\",\n      \"links\": {\n        \"posts\": {\n          \"href\": \"/api/v1.0/users/442/posts\"\n        }\n      }\n    },\n    \"links\": {\n      \"posts\": {\n        \"href\": \"/api/v1.0/blogs/452/posts\"\n      },\n      \"owner\": {\n        \"href\": \"/api/v1.0/users/442\"\n      }\n    }\n  },\n  {\n    \"id\": 329,\n    \"href\": \"/api/v1.0/blogs/329\",\n    \"name\": \"Failed to generate example for /\\\\/api\\\\/accounts\\\\/\\\\d+/ : Sorry, \\\"\\\\d+\\\" is too vague, try setting a range: \\\"\\\\d{1, 5}\\\"\",\n    \"description\": \"sturtan\",\n    \"url\": \"example.com/blogs/329\",\n    \"timestamps\": {\n      \"created_at\": \"2014-12-13T00:00:00+00:00\",\n      \"updated_at\": \"2013-09-11T00:00:00+00:00\"\n    },\n    \"owner\": {\n      \"id\": 568,\n      \"href\": \"/api/v1.0/users/568\",\n      \"first\": \"Bill\",\n      \"last\": \"Reichert\",\n      \"links\": {\n        \"posts\": {\n          \"href\": \"/api/v1.0/users/568/posts\"\n        }\n      }\n    },\n    \"links\": {\n      \"posts\": {\n        \"href\": \"/api/v1.0/blogs/329/posts\"\n      },\n      \"owner\": {\n        \"href\": \"/api/v1.0/users/568\"\n      }\n    }\n  }\n]"
                  }
                }
              }
            }
          },
          "urls": [
            {
              "verb": "GET",
              "path": "/api/v1.0/blogs",
              "version": "1.0",
              "example": "/api/v1.0/blogs"
            }
          ]
        },
        {
          "description": null,
          "name": "show",
          "metadata": {
          },
          "params": {
            "options": {
              "reference": "V1::MediaTypes::Blog"
            },
            "type": {
              "name": "Struct",
              "family": "hash",
              "id": null,
              "key": {
                "type": {
                  "name": "Symbol",
                  "family": "string",
                  "id": "Attributor-Symbol"
                }
              },
              "attributes": {
                "id": {
                  "description": "Unique identifier",
                  "type": {
                    "name": "Integer",
                    "family": "numeric",
                    "id": "Attributor-Integer"
                  },
                  "example": 197,
                  "source": "url"
                }
              }
            }
          },
          "responses": {
            "ok": {
              "description": "Standard response for successful HTTP requests.",
              "status": 200,
              "headers": {
              },
              "payload": {
                "name": "V1::MediaTypes::Blog",
                "family": "hash",
                "id": "V1-MediaTypes-Blog",
                "key": {
                  "type": {
                    "name": "Symbol",
                    "family": "string",
                    "id": "Attributor-Symbol"
                  }
                },
                "examples": {
                  "json": {
                    "content_type": "application/vnd.bloggy.blog+json",
                    "body": "{\n  \"id\": 197,\n  \"href\": \"/api/v1.0/blogs/197\",\n  \"name\": \"Failed to generate example for /\\\\/api\\\\/accounts\\\\/\\\\d+/ : Sorry, \\\"\\\\d+\\\" is too vague, try setting a range: \\\"\\\\d{1, 5}\\\"\",\n  \"description\": \"womanism\",\n  \"url\": \"example.com/blogs/197\",\n  \"timestamps\": {\n    \"created_at\": \"2012-11-02T00:00:00+00:00\",\n    \"updated_at\": \"2012-11-22T00:00:00+00:00\"\n  },\n  \"owner\": {\n    \"id\": 92,\n    \"href\": \"/api/v1.0/users/92\",\n    \"first\": \"Tracy\",\n    \"last\": \"Hackett\",\n    \"links\": {\n      \"posts\": {\n        \"href\": \"/api/v1.0/users/92/posts\"\n      }\n    }\n  },\n  \"links\": {\n    \"posts\": {\n      \"href\": \"/api/v1.0/blogs/197/posts\"\n    },\n    \"owner\": {\n      \"href\": \"/api/v1.0/users/92\"\n    }\n  }\n}"
                  }
                }
              }
            },
            "resource_not_found": {
              "description": "The requested API resource could not be found for the provided :id",
              "status": 404,
              "headers": {
              }
            }
          },
          "urls": [
            {
              "verb": "GET",
              "path": "/api/v1.0/blogs/:id",
              "version": "1.0",
              "example": "/api/v1.0/blogs/197"
            }
          ]
        },
        {
          "description": null,
          "name": "create",
          "metadata": {
          },
          "payload": {
            "options": {
              "reference": "V1::MediaTypes::Blog"
            },
            "type": {
              "name": "Struct",
              "family": "hash",
              "id": null,
              "key": {
                "type": {
                  "name": "Symbol",
                  "family": "string",
                  "id": "Attributor-Symbol"
                }
              },
              "attributes": {
                "name": {
                  "description": "Short name",
                  "required": true,
                  "options": {
                    "regexp": "(?-mix:\\/api\\/accounts\\/\\d+)"
                  },
                  "type": {
                    "name": "String",
                    "family": "string",
                    "id": "Attributor-String"
                  },
                  "example": "Failed to generate example for /\\/api\\/accounts\\/\\d+/ : Sorry, \"\\d+\" is too vague, try setting a range: \"\\d{1, 5}\""
                },
                "description": {
                  "description": "Longer description",
                  "type": {
                    "name": "String",
                    "family": "string",
                    "id": "Attributor-String"
                  },
                  "example": "womanism"
                },
                "tags": {
                  "description": "Array of tags",
                  "type": {
                    "name": "Collection",
                    "family": "array",
                    "id": null,
                    "options": {
                    },
                    "member_attribute": {
                      "type": {
                        "name": "String",
                        "family": "string",
                        "id": "Attributor-String"
                      },
                      "example": "dividingly"
                    }
                  }
                },
                "owner": {
                  "description": "Related User resource",
                  "required": true,
                  "options": {
                    "reference": "V1::MediaTypes::User"
                  },
                  "type": {
                    "name": "Struct",
                    "family": "hash",
                    "id": null,
                    "key": {
                      "type": {
                        "name": "Symbol",
                        "family": "string",
                        "id": "Attributor-Symbol"
                      }
                    },
                    "attributes": {
                      "id": {
                        "required": true,
                        "type": {
